# Script mode helper for EmbedResources.cmake. Inputs: NAMESPACE, HEADER,
# SOURCE, LIST_FILE (one "path|name" line per resource).

file(STRINGS "${LIST_FILE}" entries)
set(FILES "")
set(NAMES "")
foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 file)
    list(GET parts 1 name)
    list(APPEND FILES "${file}")
    list(APPEND NAMES "${name}")
endforeach()

get_filename_component(header_name "${HEADER}" NAME)
string(REPLACE "::" "/" ns_dir "${NAMESPACE}")

file(WRITE "${HEADER}" "// Generated by EmbedResources.cmake. Do not edit.
#pragma once

#include <optional>
#include <span>
#include <string_view>

namespace ${NAMESPACE}
{
struct Resource
{
    std::string_view name;
    std::string_view data;
};

std::span<const Resource> all();
std::optional<std::string_view> find(std::string_view name);
} // namespace ${NAMESPACE}
")

set(body "// Generated by EmbedResources.cmake. Do not edit.
#include \"${ns_dir}/${header_name}\"

#include <array>

namespace ${NAMESPACE}
{
namespace
{
")

list(LENGTH FILES count)
math(EXPR last "${count} - 1")
set(table "")
foreach(i RANGE ${last})
    list(GET FILES ${i} file)
    list(GET NAMES ${i} name)
    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Keep generated lines short enough for every compiler.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
    string(APPEND body "const unsigned char data${i}[] = {\n${bytes}0x00};\n")
    string(APPEND table "    Resource { \"${name}\", std::string_view(reinterpret_cast<const char*>(data${i}), ${size}) },\n")
endforeach()

string(APPEND body "
const std::array<Resource, ${count}> resources {{
${table}}};
} // namespace

std::span<const Resource> all()
{
    return resources;
}

std::optional<std::string_view> find(std::string_view name)
{
    for (const auto& r : resources)
        if (r.name == name)
            return r.data;
    return std::nullopt;
}
} // namespace ${NAMESPACE}
")

file(WRITE "${SOURCE}" "${body}")
